def start_screen():
    print ()
    print (" |----------------------------------------------------------------------------|")
    print (" |               /-\   |\  |   /-\   /--\ |   | |--\  /--\  |\  |             |")
    print (" |               /---\  | \ |  /---\ |     ----  |--/ |    | | \ |            |")
    print (" |               /    \|  \| /     \ \__/ |   | |  \  \__/  |  \|             |")
    print ("<|----------------------------------------------------------------------------|>")
    print ()
    print ()
    print ()
    print ("                      ,gaaaaaaaagaaaaaaaaaaaaagaaaaaaaag,    ")
    print ("                    ,aP8b    _,dYba,       ,adPb,_    d8Ya,  ")
    print ("                  ,aP\"  Yb_,dP\"   \"Yba, ,adP\"   \"Yb,_dP  \"Ya,    ")
    print ("                ,aP\"    _88\"         )888(         \"88_    \"Ya,  ")
    print ("              ,aP\"   _,dP\"Yb      ,adP\"8\"Yba,      dP\"Yb,_   \"Ya,    ")
    print ("            ,aPYb _,dP8    Yb  ,adP\"   8   \"Yba,  dP    8Yb,_ dPYa,  ")
    print ("          ,aP\"  YdP\" dP     YbdP\"      8      \"YbdP     Yb \"YbP  \"Ya,    ")
    print ("         I8aaaaaa8aaa8baaaaaa88aaaaaaaa8aaaaaaaa88aaaaaad8aaa8aaaaaa8I   ")
    print ("         `Yb,   d8a, Ya      d8b,      8      ,d8b      aP ,a8b   ,dP'   ")
    print ("           \"Yb,dP \"Ya \"8,   dI \"Yb,    8    ,dP\" Ib   ,8\" aP\" Yb,dP\" ")
    print ("             \"Y8,   \"YaI8, ,8'   \"Yb,  8  ,dP\"   `8, ,8IaP\"   ,8P\"   ")
    print ("               \"Yb,   `\"Y8ad'      \"Yb,8,dP\"      `ba8P\"'   ,dP\" ")
    print ("                 \"Yb,    `\"8,        \"Y8P\"        ,8\"'    ,dP\"   ")
    print ("                   \"Yb,    `8,         8         ,8'    ,dP\" ")
    print ("                     \"Yb,   `Ya        8        aP'   ,dP\"   ")
    print ("                       \"Yb,   \"8,      8      ,8\"   ,dP\" ")
    print ("                         \"Yb,  `8,     8     ,8'  ,dP\"   ")
    print ("                           \"Yb, `Ya    8    aP' ,dP\"     ")
    print ("                             \"Yb, \"8,  8  ,8\" ,dP\"   ")
    print ("                               \"Yb,`8, 8 ,8',dP\" ")
    print ("                                 \"Yb,Ya8aP,dP\"   ")
    print ("                                   \"Y88888P\" ")
    print ("                                     \"Y8P\"   ")
    print ("                                       \" ")
    print ()
    print ()
    print ("<                For optimal experience, please resize window                  >")
    print ()
    print ("                             Press enter to continue      ")
    print ()
    print ()
    input ()
    print ()

def winscreen():
    transition()
    print ("                                      YOU WIN!")
    print ()
    print ()
    print ()
    print ()
    print ("                           You've defeated the Sorcerer")
    print ()
    print ()
    print ()
    input ()
    thankyou(hp, attackdmg, armor, inventory, ending, difficulty, boy, friendship, timetravel, secret_wait, secret_glasses, manual, temple)

def losescreen():
    transition()
    print ()
    print ()
    print ()
    print ()
    print ()
    print ("                                     YOU DIED!")
    print ()
    print ()
    print ()
    print ()
    print ("                 You've fallen in battle to the forces of evil.")
    print ()
    print ()
    print ()
    input ()
    thankyou(hp, attackdmg, armor, inventory, ending, difficulty, boy, friendship, timetravel, secret_wait, secret_glasses, manual, temple)

def thankyou(hp, attackdmg, armor, inventory, ending, difficulty, boy, friendship, timetravel, secret_wait, secret_glasses, manual, temple):
#    global code
    print ("Thank you for playing!")
    print ()
    print ("HP:", hp)
    print ("Attack:", attackdmg)
    print ("Armor:", armor)
    print ("Inventory:", inventory)
    print ()
    print ("Ending:", ending)
    print ("Difficulty:", difficulty)
    print ("Boy:", boy)
    print ("Friendship:", friendship)
    if temple == True:
        print ("time traveled:", timetravel)
        print ()
        print ("Secret 1:", secret_wait)
        print ("Secret 2:", secret_glasses)
#       if ending == '3':
#       print ("Secret Code:", code)
    print ()
    while True:
        answer = input("Would you like to read the manual before you leave? (yes/no) ")
        if answer == 'yes':
            print ()
            print (manual)
            print ()
            print ("Thank you for playing! The game will now exit")
            input ()
            exit ()
        else:
            print ()
            print ("Bye! The game will now exit")
            input()
            exit ()

def transition():
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print (' 0                                                                           0')
    print ('  0                                                                         0')
    print ('   0                                                                       0')
    print ('    0                                                                     0')
    print ('     0                                                                   0')
    print ('      0                                                                 0')
    print ('       0                                                               0')
    print ('        0                                                             0')
    print ('         0                                                           0')
    print ('          0                                                         0')
    print ('           0                                                       0')
    print ('            0                                                     0')
    print ('             0                                                   0')
    print ('              0                                                 0')
    print ('               0                                               0')
    print ('                0                                             0')
    print ('                 0                                           0')
    print ('                  0                                         0')
    print ('                   0                                       0')
    print ('                    0                                     0')
    print ('                     0                                   0')
    print ('                      0                                 0')
    print ('                       0                               0')
    print ('                        0                             0')
    print ('                         0                           0')
    print ('                          0                         0')
    print ('                           0                       0')
    print ('                            0                     0')
    print ('                             0                   0')
    print ('                              0                 0')
    print ('                               0               0')
    print ('                                0             0')
    print ('                                 0           0')
    print ('                                  0         0')
    print ('                                   0       0')
    print ('                                    0     0')
    print ('                                     0   0')
    print ('                                      0 0')
    print ('                                       0')
    print ('                                      0 0')
    print ('                                     0   0')
    print ('                                    0     0')
    print ('                                   0       0')
    print ('                                  0         0')
    print ('                                 0           0')
    print ('                                0             0')
    print ('                               0               0')
    print ('                              0                 0')
    print ('                             0                   0')
    print ('                            0                     0')
    print ('                           0                       0')
    print ('                          0                         0')
    print ('                         0                           0')
    print ('                        0                             0')
    print ('                       0                               0')
    print ('                      0                                 0')
    print ('                     0                                   0')
    print ('                    0                                     0')
    print ('                   0                                       0')
    print ('                  0                                         0')
    print ('                 0                                           0')
    print ('                0                                             0')
    print ('               0                                               0')
    print ('              0                                                 0')
    print ('             0                                                   0')
    print ('            0                                                     0')
    print ('           0                                                       0')
    print ('          0                                                         0')
    print ('         0                                                           0')
    print ('        0                                                             0')
    print ('       0                                                               0')
    print ('      0                                                                 0')
    print ('     0                                                                   0')
    print ('    0                                                                     0')
    print ('   0                                                                       0')
    print ('  0                                                                         0')
    print (' 0                                                                           0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print (' 0                                                                           0')
    print ('  0                                                                         0')
    print ('   0                                                                       0')
    print ('    0                                                                     0')
    print ('     0                                                                   0')
    print ('      0                                                                 0')
    print ('       0                                                               0')
    print ('        0                                                             0')
    print ('         0                                                           0')
    print ('          0                                                         0')
    print ('           0                                                       0')
    print ('            0                                                     0')
    print ('             0                                                   0')
    print ('              0                                                 0')
    print ('               0                                               0')
    print ('                0                                             0')
    print ('                 0                                           0')
    print ('                  0                                         0')
    print ('                   0                                       0')
    print ('                    0                                     0')
    print ('                     0                                   0')
    print ('                      0                                 0')
    print ('                       0                               0')
    print ('                        0                             0')
    print ('                         0                           0')
    print ('                          0                         0')
    print ('                           0                       0')
    print ('                            0                     0')
    print ('                             0                   0')
    print ('                              0                 0')
    print ('                               0               0')
    print ('                                0             0')
    print ('                                 0           0')
    print ('                                  0         0')
    print ('                                   0       0')
    print ('                                    0     0')
    print ('                                     0   0')
    print ('                                      0 0')
    print ('                                       0')
    print ('                                      0 0')
    print ('                                     0   0')
    print ('                                    0     0')
    print ('                                   0       0')
    print ('                                  0         0')
    print ('                                 0           0')
    print ('                                0             0')
    print ('                               0               0')
    print ('                              0                 0')
    print ('                             0                   0')
    print ('                            0                     0')
    print ('                           0                       0')
    print ('                          0                         0')
    print ('                         0                           0')
    print ('                        0                             0')
    print ('                       0                               0')
    print ('                      0                                 0')
    print ('                     0                                   0')
    print ('                    0                                     0')
    print ('                   0                                       0')
    print ('                  0                                         0')
    print ('                 0                                           0')
    print ('                0                                             0')
    print ('               0                                               0')
    print ('              0                                                 0')
    print ('             0                                                   0')
    print ('            0                                                     0')
    print ('           0                                                       0')
    print ('          0                                                         0')
    print ('         0                                                           0')
    print ('        0                                                             0')
    print ('       0                                                               0')
    print ('      0                                                                 0')
    print ('     0                                                                   0')
    print ('    0                                                                     0')
    print ('   0                                                                       0')
    print ('  0                                                                         0')
    print (' 0                                                                           0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
    print ('0                                                                             0')
